### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by kolbacer** [Sewer56/Heroes.Graphics.Essentials.ReloadedII#4]
Is it possible to configure anti-aliasing with this mod?

**Comment by Sewer56** [comment]
The original Graphics Essentials supported it but I decided not to add features that could instead be added using your vendor's graphics control panel.

Part of the reason was the lack of libraries to work with Direct3D 8 for .NET. I don't want to drop in d3d8to9 as that would involve modifying the game folder, which I prefer for people to not do. Reloaded and (almost) every mod that exists for it don't modify the game files directly, which means that removing Reloaded is as simple as removing the mod loader folder.

**Comment by kolbacer** [comment]
> The original Graphics Essentials supported it but I decided not to add features that could instead be added using your vendor's graphics control panel.

Well, Issue closed. But sorry for dumb question, how can I do that? Changes in my NVIDIA control panel (for Tsonic_win.exe) affect nothing. 
However, utility "dgVoodoo" could change source of control. (I afraid to use it with Reloaded)
Thanks in advance for your reply.
